version: '3.1'

services:
  telegram-proxy:
    image: telegrammessenger/proxy:latest
    restart: unless-stopped
    ports:
      - "943:443"
    volumes:
        - "$(pwd)/data:/data"
    env_file:
        - ./config.env
